### ISSUE TITLE
For Loupedeck Marketplace

### ISSUE THREAD

**Issue by Limeqvist** [devleaks/streamdecks#2]
Hi!

I would be very keen on hosting this on the Loupedeck Marketplace once it's finished. You can email me att emil.lindqvist@loupedeck.com for specifics about it and I also recommend joining our dev discord if you're not there already :)

**Comment by devleaks** [comment]
No problem. Code is here. Not updated for a long time, but I'll try to keep it in sych [with another](https://github.com/devleaks/cockpitdecks) dev that I maintain more actively. Thanks.
